sudo: required
dist: trusty
language: ruby
rvm:
  - 2.5
before_install:
  - gem install -v 2.0.2 bundler --no-rdoc --no-ri
  - bundle _2.0.2_ install
script:
  - bundle exec rake spec
  - gem build cfn_manage.gemspec
  - gem install cfn_manage-*.gem
  - cfn_manage --version
deploy:
  provider: rubygems
  api_key: "${RUBYGEMS_API_KEY}"
  gem: cfn_manage
  on:
   all_branches: true
   condition: $TRAVIS_BRANCH =~ ^develop|master &&  $TRAVIS_EVENT_TYPE =~ ^push|api$ && $TRAVIS_REPO_SLUG == "base2Services/cfn-start-stop-stack"
